logger:
  default: info
  logs:
    custom_components.powertag_gateway: debug

debugpy:

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.17.0.0/16
        - 127.0.0.1
        - ::1
      allow_bypass_login: true
    - type: homeassistant


# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
